### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by graphixillusion** [bettercallshao/kwt#46]
Hi there. I just update to last kwt version v0.6.4-20230901235817 (Windows build) and i'm getting this error when i start some command. Previous version works good.

```
goroutine 1 [running]:
main.act(0xc0001e24c0)
        /home/circleci/project/kwt/cmd/kwt/standalone.go:89 +0x636
github.com/urfave/cli/v2.(*Command).Run(0xc0001a8160, 0xc0001e24c0, {0xc0001e86b0, 0x1, 0x1})
        /home/circleci/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:274 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc0001a8420, 0xc0001e2400, {0xc000061e80, 0x2, 0x2})
        /home/circleci/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*Command).Run(0xc0001a91e0, 0xc0001e22c0, {0xc000036080, 0x3, 0x4})
        /home/circleci/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/command.go:267 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc0001ea000, {0xaa2408?, 0xc00001c0d8}, {0xc000036080, 0x3, 0x4})
        /home/circleci/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        /home/circleci/go/pkg/mod/github.com/urfave/cli/v2@v2.25.7/app.go:309
main.main()
        /home/circleci/project/kwt/cmd/kwt/main.go:168 +0x98d
```

**Comment by graphixillusion** [comment]
Fixed in v0.6.5
